//
//  ToolCall.swift
//
//
//  Created by James Rochabrun on 11/14/23.
//

import Foundation

// MARK: - ToolCall

public struct ToolCall: Codable {
  public init(
    index: Int? = nil,
    id: String?,
    type: String = "function",
    function: FunctionCall,
    extraContent: ExtraContent? = nil)
  {
    self.index = index
    self.id = id
    self.type = type
    self.function = function
    self.extraContent = extraContent
  }

  public let index: Int?
  /// The ID of the tool call.
  public let id: String?
  /// The type of the tool. Currently, only `function` is supported.
  public let type: String?
  /// The function that the model called.
  public let function: FunctionCall
  /// Extra content from providers like Google Gemini (contains thought_signature for reasoning models)
  public let extraContent: ExtraContent?

  enum CodingKeys: String, CodingKey {
    case index
    case id
    case type
    case function
    case extraContent = "extra_content"
  }

  // MARK: - ExtraContent (Gemini thought_signature support)

  /// Extra content returned by providers, used for Gemini's thought_signature
  public struct ExtraContent: Codable {
    public let google: GoogleContent?

    public init(google: GoogleContent?) {
      self.google = google
    }

    /// Google-specific content containing thought_signature
    public struct GoogleContent: Codable {
      /// The thought signature required for Gemini 3 models with tool calls.
      /// Must be passed back in subsequent requests to preserve reasoning state.
      public let thoughtSignature: String?

      public init(thoughtSignature: String?) {
        self.thoughtSignature = thoughtSignature
      }

      enum CodingKeys: String, CodingKey {
        case thoughtSignature = "thought_signature"
      }
    }
  }
}

// MARK: - FunctionCall

public struct FunctionCall: Codable {
  /// The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.
  public let arguments: String
  /// The name of the function to call.
  public let name: String?

  public init(
    arguments: String,
    name: String)
  {
    self.arguments = arguments
    self.name = name
  }
}
